/*
 * obj2c.c - bakes a vehicle (OBJ mesh + PNG texture + metadata) into a C
 * header of static arrays.
 *
 * Not used by the default build on either platform: GameCube now reads
 * assets/vehicles.json / .obj / .png straight off the disc at runtime
 * through the "gcdvd:" device (see gcdvd.c), the same as desktop reads
 * them off the regular filesystem. This host-side tool (built and run on
 * your desktop, never on the GameCube) is kept around for anyone who
 * wants an alternative no-disc-access fallback vehicle baked directly
 * into the .dol as `static const` data plus tiny accessors - wire the
 * generated header's *_get_baked()/*_texture_rgba into game.c yourself
 * if you need that.
 *
 * Reuses obj_loader.c's OBJ parser and image_load.c's PNG decoder
 * directly (both compiled with PLATFORM_PC defined) so each file format
 * is only understood in one place, shared with the desktop build.
 *
 * Usage: obj2c <input.obj> <input.png> <output.h> <array_prefix> <id> <name> <yaw_offset_deg>
 * Example: obj2c assets/vehicles/mach_bike/bike.obj assets/vehicles/mach_bike/bike.png \
 *                 src/mach_bike_baked.h mach_bike 1 "Mach Bike" 180
 */
#define PLATFORM_PC
#include "../src/obj_loader.c"
#include "../src/image_load.c"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

static void upper_ident(const char *s, char *out, size_t outsz) {
    size_t i;
    for (i = 0; s[i] && i + 1 < outsz; ++i)
        out[i] = (char)((s[i] >= 'a' && s[i] <= 'z') ? s[i] - 'a' + 'A' : s[i]);
    out[i] = '\0';
}

int main(int argc, char **argv) {
    Mesh m;
    FILE *out;
    int i;
    char guard[128];
    const char *prefix;
    int vehicle_id;
    const char *vehicle_name;
    float yaw_offset_deg;
    unsigned char *pixels;
    int tex_w = 0, tex_h = 0;

    if (argc != 8) {
        fprintf(stderr,
               "usage: %s <input.obj> <input.png> <output.h> <array_prefix> <id> <name> <yaw_offset_deg>\n",
               argv[0]);
        return 1;
    }
    prefix         = argv[4];
    vehicle_id     = atoi(argv[5]);
    vehicle_name   = argv[6];
    yaw_offset_deg = (float)atof(argv[7]);

    if (!mesh_load_obj(&m, argv[1])) {
        fprintf(stderr, "obj2c: failed to load '%s'\n", argv[1]);
        return 1;
    }
    mesh_recenter_to_ground(&m);

    pixels = image_load_rgba(argv[2], &tex_w, &tex_h);
    if (!pixels) {
        fprintf(stderr, "obj2c: failed to load '%s'\n", argv[2]);
        mesh_free(&m);
        return 1;
    }

    out = fopen(argv[3], "w");
    if (!out) {
        fprintf(stderr, "obj2c: failed to open '%s' for writing\n", argv[3]);
        mesh_free(&m);
        image_free(pixels);
        return 1;
    }

    upper_ident(prefix, guard, sizeof(guard));

    fprintf(out, "/* Auto-generated by tools/obj2c.c from %s + %s. Do not edit by\n", argv[1], argv[2]);
    fprintf(out, "   hand; re-run tools/obj2c.c if the source model/texture change. */\n");
    fprintf(out, "#ifndef %s_H\n#define %s_H\n\n", guard, guard);
    fprintf(out, "#include <string.h>\n");
    fprintf(out, "#include \"obj_loader.h\"\n\n");

    fprintf(out, "#define %s_ID %d\n", guard, vehicle_id);
    fprintf(out, "#define %s_NAME \"%s\"\n", guard, vehicle_name);
    fprintf(out, "#define %s_YAW_OFFSET_DEG %.6ff\n\n", guard, yaw_offset_deg);

    fprintf(out, "static const MeshVertex %s_verts[] = {\n", prefix);
    for (i = 0; i < m.vert_count; ++i) {
        MeshVertex *v = &m.verts[i];
        fprintf(out, "    { {%.6ff,%.6ff,%.6ff}, {%.6ff,%.6ff,%.6ff}, %.6ff,%.6ff, %d },\n",
               v->pos.x, v->pos.y, v->pos.z,
               v->normal.x, v->normal.y, v->normal.z,
               v->u, v->v,
               v->mtl);
    }
    fprintf(out, "};\n\n");

    fprintf(out, "static const MeshMaterial %s_materials[] = {\n", prefix);
    for (i = 0; i < m.material_count; ++i) {
        MeshMaterial *mt = &m.materials[i];
        fprintf(out, "    { \"%s\", %.6ff, %.6ff, %.6ff },\n", mt->name, mt->r, mt->g, mt->b);
    }
    fprintf(out, "};\n\n");

    fprintf(out, "#define %s_VERT_COUNT ((int)(sizeof(%s_verts)/sizeof(%s_verts[0])))\n",
           guard, prefix, prefix);
    fprintf(out, "#define %s_MATERIAL_COUNT ((int)(sizeof(%s_materials)/sizeof(%s_materials[0])))\n\n",
           guard, prefix, prefix);

    fprintf(out, "/* Fills `out` with the baked mesh. `out` does not own the arrays\n");
    fprintf(out, "   (they are static const), so never call mesh_free() on it. */\n");
    fprintf(out, "static inline void %s_get_baked(Mesh *out) {\n", prefix);
    fprintf(out, "    out->verts = (MeshVertex *)%s_verts;\n", prefix);
    fprintf(out, "    out->vert_count = %s_VERT_COUNT;\n", guard);
    fprintf(out, "    memcpy(out->materials, %s_materials, sizeof(%s_materials));\n", prefix, prefix);
    fprintf(out, "    out->material_count = %s_MATERIAL_COUNT;\n", guard);
    fprintf(out, "    out->bounds_min = vec3(%.6ff,%.6ff,%.6ff);\n",
           m.bounds_min.x, m.bounds_min.y, m.bounds_min.z);
    fprintf(out, "    out->bounds_max = vec3(%.6ff,%.6ff,%.6ff);\n",
           m.bounds_max.x, m.bounds_max.y, m.bounds_max.z);
    fprintf(out, "}\n\n");

    fprintf(out, "#define %s_TEXTURE_WIDTH  %d\n", guard, tex_w);
    fprintf(out, "#define %s_TEXTURE_HEIGHT %d\n\n", guard, tex_h);
    fprintf(out, "/* Raw top-to-bottom RGBA8 pixels (pre-PNG-decode), ready for\n");
    fprintf(out, "   render_texture_create() - see mach_bike_get_baked()'s use in game.c. */\n");
    fprintf(out, "static const unsigned char %s_texture_rgba[] = {\n", prefix);
    {
        int n = tex_w * tex_h * 4;
        for (i = 0; i < n; ++i) {
            fprintf(out, "%u,", pixels[i]);
            if ((i & 31) == 31) fprintf(out, "\n");
        }
        fprintf(out, "\n");
    }
    fprintf(out, "};\n\n");

    fprintf(out, "#endif /* %s_H */\n", guard);
    fclose(out);

    fprintf(stderr, "obj2c: wrote %s (%d verts, %d materials, %dx%d texture) from %s + %s\n",
           argv[3], m.vert_count, m.material_count, tex_w, tex_h, argv[1], argv[2]);

    mesh_free(&m);
    image_free(pixels);
    return 0;
}
